memory: 2048
ip: 172.28.128.102
ports:
- send: 8082
  to: 80
fs:
  folders:
    magento2:
      host: data/web/magento2
      guest: /data/web/magento2
    magento1:
      host: data/web/public
      guest: /data/web/public
    nginx:
      host: data/web/nginx/
      guest: /data/web/nginx/
hostmanager:
  extra-aliases:
    - my-custom-store-url1.local
    - my-custom-store-url2.local
